export * as grpcIdentityModel from './grpc/indykite/identity/v1beta2/model';
export * as grpcIdentityAPI from './grpc/indykite/identity/v1beta2/identity_management_api';
export * as grpcIdentityAttributes from './grpc/indykite/identity/v1beta2/attributes';
export * from './sdk/authorization';
export * from './sdk/authorization';
export * from './sdk/identity';
export * from './sdk/config';
export { IdentityKnowledgeClient } from './sdk/knowledge';
export * from './sdk/knowledgev2';
export * from './sdk/http';
export * from './sdk/ingest';
export * from './sdk/model';
export { DeleteDigitalTwinRequest } from './grpc/indykite/identity/v1beta2/identity_management_api';
