// @generated by protobuf-ts 2.9.0 with parameter long_type_string,client_grpc1,generate_dependencies
// @generated from protobuf file "indykite/ingest/v1beta3/ingest_api.proto" (package "indykite.ingest.v1beta3", syntax proto3)
// tslint:disable
//
// Copyright (c) 2023 IndyKite
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Status } from "../../../google/rpc/status";
import { RecordError } from "./model";
import { Record } from "./model";
import { DeleteData_RelationshipPropertyMatch } from "./model";
import { DeleteData_NodePropertyMatch } from "./model";
import { NodeMatch } from "./model";
import { Relationship } from "./model";
import { Info } from "./model";
import { Node } from "../../knowledge/objects/v1beta1/ikg";
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchUpsertNodesRequest
 */
export interface BatchUpsertNodesRequest {
    /**
     * @generated from protobuf field: repeated indykite.knowledge.objects.v1beta1.Node nodes = 1;
     */
    nodes: Node[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchUpsertNodesResponse
 */
export interface BatchUpsertNodesResponse {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.Info results = 1;
     */
    results: Info[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchUpsertRelationshipsRequest
 */
export interface BatchUpsertRelationshipsRequest {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.Relationship relationships = 1;
     */
    relationships: Relationship[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchUpsertRelationshipsResponse
 */
export interface BatchUpsertRelationshipsResponse {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.Info results = 1;
     */
    results: Info[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchDeleteNodesRequest
 */
export interface BatchDeleteNodesRequest {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.NodeMatch nodes = 1;
     */
    nodes: NodeMatch[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchDeleteNodesResponse
 */
export interface BatchDeleteNodesResponse {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.Info results = 1;
     */
    results: Info[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchDeleteRelationshipsRequest
 */
export interface BatchDeleteRelationshipsRequest {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.Relationship relationships = 1;
     */
    relationships: Relationship[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchDeleteRelationshipsResponse
 */
export interface BatchDeleteRelationshipsResponse {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.Info results = 1;
     */
    results: Info[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchDeleteNodePropertiesRequest
 */
export interface BatchDeleteNodePropertiesRequest {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.DeleteData.NodePropertyMatch node_properties = 1;
     */
    nodeProperties: DeleteData_NodePropertyMatch[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchDeleteNodePropertiesResponse
 */
export interface BatchDeleteNodePropertiesResponse {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.Info results = 1;
     */
    results: Info[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchDeleteRelationshipPropertiesRequest
 */
export interface BatchDeleteRelationshipPropertiesRequest {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.DeleteData.RelationshipPropertyMatch relationship_properties = 1;
     */
    relationshipProperties: DeleteData_RelationshipPropertyMatch[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.BatchDeleteRelationshipPropertiesResponse
 */
export interface BatchDeleteRelationshipPropertiesResponse {
    /**
     * @generated from protobuf field: repeated indykite.ingest.v1beta3.Info results = 1;
     */
    results: Info[];
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.StreamRecordsRequest
 */
export interface StreamRecordsRequest {
    /**
     * @generated from protobuf field: indykite.ingest.v1beta3.Record record = 1;
     */
    record?: Record;
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.StreamRecordsResponse
 */
export interface StreamRecordsResponse {
    /**
     * @generated from protobuf field: string record_id = 1;
     */
    recordId: string;
    /**
     * @generated from protobuf field: uint32 record_index = 2;
     */
    recordIndex: number;
    /**
     * @generated from protobuf oneof: error
     */
    error: {
        oneofKind: "recordError";
        /**
         * @generated from protobuf field: indykite.ingest.v1beta3.RecordError record_error = 3;
         */
        recordError: RecordError;
    } | {
        oneofKind: "statusError";
        /**
         * @generated from protobuf field: google.rpc.Status status_error = 4;
         */
        statusError: Status;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: indykite.ingest.v1beta3.Info info = 5;
     */
    info?: Info;
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.IngestRecordRequest
 */
export interface IngestRecordRequest {
    /**
     * @generated from protobuf field: indykite.ingest.v1beta3.Record record = 1;
     */
    record?: Record;
}
/**
 * @generated from protobuf message indykite.ingest.v1beta3.IngestRecordResponse
 */
export interface IngestRecordResponse {
    /**
     * @generated from protobuf field: string record_id = 1;
     */
    recordId: string;
    /**
     * @generated from protobuf field: indykite.ingest.v1beta3.Info info = 5;
     */
    info?: Info;
}
// @generated message type with reflection information, may provide speed optimized methods
class BatchUpsertNodesRequest$Type extends MessageType<BatchUpsertNodesRequest> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchUpsertNodesRequest", [
            { no: 1, name: "nodes", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Node, options: { "validate.rules": { repeated: { minItems: "1", maxItems: "250" } } } }
        ]);
    }
    create(value?: PartialMessage<BatchUpsertNodesRequest>): BatchUpsertNodesRequest {
        const message = { nodes: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchUpsertNodesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchUpsertNodesRequest): BatchUpsertNodesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.knowledge.objects.v1beta1.Node nodes */ 1:
                    message.nodes.push(Node.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchUpsertNodesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.knowledge.objects.v1beta1.Node nodes = 1; */
        for (let i = 0; i < message.nodes.length; i++)
            Node.internalBinaryWrite(message.nodes[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchUpsertNodesRequest
 */
export const BatchUpsertNodesRequest = new BatchUpsertNodesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchUpsertNodesResponse$Type extends MessageType<BatchUpsertNodesResponse> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchUpsertNodesResponse", [
            { no: 1, name: "results", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Info }
        ]);
    }
    create(value?: PartialMessage<BatchUpsertNodesResponse>): BatchUpsertNodesResponse {
        const message = { results: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchUpsertNodesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchUpsertNodesResponse): BatchUpsertNodesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.Info results */ 1:
                    message.results.push(Info.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchUpsertNodesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.Info results = 1; */
        for (let i = 0; i < message.results.length; i++)
            Info.internalBinaryWrite(message.results[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchUpsertNodesResponse
 */
export const BatchUpsertNodesResponse = new BatchUpsertNodesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchUpsertRelationshipsRequest$Type extends MessageType<BatchUpsertRelationshipsRequest> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchUpsertRelationshipsRequest", [
            { no: 1, name: "relationships", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Relationship, options: { "validate.rules": { repeated: { minItems: "1", maxItems: "250" } } } }
        ]);
    }
    create(value?: PartialMessage<BatchUpsertRelationshipsRequest>): BatchUpsertRelationshipsRequest {
        const message = { relationships: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchUpsertRelationshipsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchUpsertRelationshipsRequest): BatchUpsertRelationshipsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.Relationship relationships */ 1:
                    message.relationships.push(Relationship.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchUpsertRelationshipsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.Relationship relationships = 1; */
        for (let i = 0; i < message.relationships.length; i++)
            Relationship.internalBinaryWrite(message.relationships[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchUpsertRelationshipsRequest
 */
export const BatchUpsertRelationshipsRequest = new BatchUpsertRelationshipsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchUpsertRelationshipsResponse$Type extends MessageType<BatchUpsertRelationshipsResponse> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchUpsertRelationshipsResponse", [
            { no: 1, name: "results", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Info }
        ]);
    }
    create(value?: PartialMessage<BatchUpsertRelationshipsResponse>): BatchUpsertRelationshipsResponse {
        const message = { results: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchUpsertRelationshipsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchUpsertRelationshipsResponse): BatchUpsertRelationshipsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.Info results */ 1:
                    message.results.push(Info.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchUpsertRelationshipsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.Info results = 1; */
        for (let i = 0; i < message.results.length; i++)
            Info.internalBinaryWrite(message.results[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchUpsertRelationshipsResponse
 */
export const BatchUpsertRelationshipsResponse = new BatchUpsertRelationshipsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchDeleteNodesRequest$Type extends MessageType<BatchDeleteNodesRequest> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchDeleteNodesRequest", [
            { no: 1, name: "nodes", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => NodeMatch, options: { "validate.rules": { repeated: { minItems: "1", maxItems: "250" } } } }
        ]);
    }
    create(value?: PartialMessage<BatchDeleteNodesRequest>): BatchDeleteNodesRequest {
        const message = { nodes: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchDeleteNodesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchDeleteNodesRequest): BatchDeleteNodesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.NodeMatch nodes */ 1:
                    message.nodes.push(NodeMatch.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchDeleteNodesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.NodeMatch nodes = 1; */
        for (let i = 0; i < message.nodes.length; i++)
            NodeMatch.internalBinaryWrite(message.nodes[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchDeleteNodesRequest
 */
export const BatchDeleteNodesRequest = new BatchDeleteNodesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchDeleteNodesResponse$Type extends MessageType<BatchDeleteNodesResponse> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchDeleteNodesResponse", [
            { no: 1, name: "results", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Info }
        ]);
    }
    create(value?: PartialMessage<BatchDeleteNodesResponse>): BatchDeleteNodesResponse {
        const message = { results: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchDeleteNodesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchDeleteNodesResponse): BatchDeleteNodesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.Info results */ 1:
                    message.results.push(Info.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchDeleteNodesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.Info results = 1; */
        for (let i = 0; i < message.results.length; i++)
            Info.internalBinaryWrite(message.results[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchDeleteNodesResponse
 */
export const BatchDeleteNodesResponse = new BatchDeleteNodesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchDeleteRelationshipsRequest$Type extends MessageType<BatchDeleteRelationshipsRequest> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchDeleteRelationshipsRequest", [
            { no: 1, name: "relationships", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Relationship, options: { "validate.rules": { repeated: { minItems: "1", maxItems: "250" } } } }
        ]);
    }
    create(value?: PartialMessage<BatchDeleteRelationshipsRequest>): BatchDeleteRelationshipsRequest {
        const message = { relationships: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchDeleteRelationshipsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchDeleteRelationshipsRequest): BatchDeleteRelationshipsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.Relationship relationships */ 1:
                    message.relationships.push(Relationship.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchDeleteRelationshipsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.Relationship relationships = 1; */
        for (let i = 0; i < message.relationships.length; i++)
            Relationship.internalBinaryWrite(message.relationships[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchDeleteRelationshipsRequest
 */
export const BatchDeleteRelationshipsRequest = new BatchDeleteRelationshipsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchDeleteRelationshipsResponse$Type extends MessageType<BatchDeleteRelationshipsResponse> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchDeleteRelationshipsResponse", [
            { no: 1, name: "results", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Info }
        ]);
    }
    create(value?: PartialMessage<BatchDeleteRelationshipsResponse>): BatchDeleteRelationshipsResponse {
        const message = { results: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchDeleteRelationshipsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchDeleteRelationshipsResponse): BatchDeleteRelationshipsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.Info results */ 1:
                    message.results.push(Info.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchDeleteRelationshipsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.Info results = 1; */
        for (let i = 0; i < message.results.length; i++)
            Info.internalBinaryWrite(message.results[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchDeleteRelationshipsResponse
 */
export const BatchDeleteRelationshipsResponse = new BatchDeleteRelationshipsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchDeleteNodePropertiesRequest$Type extends MessageType<BatchDeleteNodePropertiesRequest> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchDeleteNodePropertiesRequest", [
            { no: 1, name: "node_properties", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => DeleteData_NodePropertyMatch, options: { "validate.rules": { repeated: { minItems: "1", maxItems: "250" } } } }
        ]);
    }
    create(value?: PartialMessage<BatchDeleteNodePropertiesRequest>): BatchDeleteNodePropertiesRequest {
        const message = { nodeProperties: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchDeleteNodePropertiesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchDeleteNodePropertiesRequest): BatchDeleteNodePropertiesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.DeleteData.NodePropertyMatch node_properties */ 1:
                    message.nodeProperties.push(DeleteData_NodePropertyMatch.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchDeleteNodePropertiesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.DeleteData.NodePropertyMatch node_properties = 1; */
        for (let i = 0; i < message.nodeProperties.length; i++)
            DeleteData_NodePropertyMatch.internalBinaryWrite(message.nodeProperties[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchDeleteNodePropertiesRequest
 */
export const BatchDeleteNodePropertiesRequest = new BatchDeleteNodePropertiesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchDeleteNodePropertiesResponse$Type extends MessageType<BatchDeleteNodePropertiesResponse> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchDeleteNodePropertiesResponse", [
            { no: 1, name: "results", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Info }
        ]);
    }
    create(value?: PartialMessage<BatchDeleteNodePropertiesResponse>): BatchDeleteNodePropertiesResponse {
        const message = { results: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchDeleteNodePropertiesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchDeleteNodePropertiesResponse): BatchDeleteNodePropertiesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.Info results */ 1:
                    message.results.push(Info.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchDeleteNodePropertiesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.Info results = 1; */
        for (let i = 0; i < message.results.length; i++)
            Info.internalBinaryWrite(message.results[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchDeleteNodePropertiesResponse
 */
export const BatchDeleteNodePropertiesResponse = new BatchDeleteNodePropertiesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchDeleteRelationshipPropertiesRequest$Type extends MessageType<BatchDeleteRelationshipPropertiesRequest> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchDeleteRelationshipPropertiesRequest", [
            { no: 1, name: "relationship_properties", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => DeleteData_RelationshipPropertyMatch, options: { "validate.rules": { repeated: { minItems: "1", maxItems: "250" } } } }
        ]);
    }
    create(value?: PartialMessage<BatchDeleteRelationshipPropertiesRequest>): BatchDeleteRelationshipPropertiesRequest {
        const message = { relationshipProperties: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchDeleteRelationshipPropertiesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchDeleteRelationshipPropertiesRequest): BatchDeleteRelationshipPropertiesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.DeleteData.RelationshipPropertyMatch relationship_properties */ 1:
                    message.relationshipProperties.push(DeleteData_RelationshipPropertyMatch.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchDeleteRelationshipPropertiesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.DeleteData.RelationshipPropertyMatch relationship_properties = 1; */
        for (let i = 0; i < message.relationshipProperties.length; i++)
            DeleteData_RelationshipPropertyMatch.internalBinaryWrite(message.relationshipProperties[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchDeleteRelationshipPropertiesRequest
 */
export const BatchDeleteRelationshipPropertiesRequest = new BatchDeleteRelationshipPropertiesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchDeleteRelationshipPropertiesResponse$Type extends MessageType<BatchDeleteRelationshipPropertiesResponse> {
    constructor() {
        super("indykite.ingest.v1beta3.BatchDeleteRelationshipPropertiesResponse", [
            { no: 1, name: "results", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Info }
        ]);
    }
    create(value?: PartialMessage<BatchDeleteRelationshipPropertiesResponse>): BatchDeleteRelationshipPropertiesResponse {
        const message = { results: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BatchDeleteRelationshipPropertiesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchDeleteRelationshipPropertiesResponse): BatchDeleteRelationshipPropertiesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated indykite.ingest.v1beta3.Info results */ 1:
                    message.results.push(Info.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchDeleteRelationshipPropertiesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated indykite.ingest.v1beta3.Info results = 1; */
        for (let i = 0; i < message.results.length; i++)
            Info.internalBinaryWrite(message.results[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.BatchDeleteRelationshipPropertiesResponse
 */
export const BatchDeleteRelationshipPropertiesResponse = new BatchDeleteRelationshipPropertiesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StreamRecordsRequest$Type extends MessageType<StreamRecordsRequest> {
    constructor() {
        super("indykite.ingest.v1beta3.StreamRecordsRequest", [
            { no: 1, name: "record", kind: "message", T: () => Record, options: { "validate.rules": { message: { required: true } } } }
        ]);
    }
    create(value?: PartialMessage<StreamRecordsRequest>): StreamRecordsRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<StreamRecordsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamRecordsRequest): StreamRecordsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* indykite.ingest.v1beta3.Record record */ 1:
                    message.record = Record.internalBinaryRead(reader, reader.uint32(), options, message.record);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamRecordsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* indykite.ingest.v1beta3.Record record = 1; */
        if (message.record)
            Record.internalBinaryWrite(message.record, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.StreamRecordsRequest
 */
export const StreamRecordsRequest = new StreamRecordsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StreamRecordsResponse$Type extends MessageType<StreamRecordsResponse> {
    constructor() {
        super("indykite.ingest.v1beta3.StreamRecordsResponse", [
            { no: 1, name: "record_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "record_index", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "record_error", kind: "message", oneof: "error", T: () => RecordError },
            { no: 4, name: "status_error", kind: "message", oneof: "error", T: () => Status },
            { no: 5, name: "info", kind: "message", T: () => Info }
        ]);
    }
    create(value?: PartialMessage<StreamRecordsResponse>): StreamRecordsResponse {
        const message = { recordId: "", recordIndex: 0, error: { oneofKind: undefined } };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<StreamRecordsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamRecordsResponse): StreamRecordsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string record_id */ 1:
                    message.recordId = reader.string();
                    break;
                case /* uint32 record_index */ 2:
                    message.recordIndex = reader.uint32();
                    break;
                case /* indykite.ingest.v1beta3.RecordError record_error */ 3:
                    message.error = {
                        oneofKind: "recordError",
                        recordError: RecordError.internalBinaryRead(reader, reader.uint32(), options, (message.error as any).recordError)
                    };
                    break;
                case /* google.rpc.Status status_error */ 4:
                    message.error = {
                        oneofKind: "statusError",
                        statusError: Status.internalBinaryRead(reader, reader.uint32(), options, (message.error as any).statusError)
                    };
                    break;
                case /* indykite.ingest.v1beta3.Info info */ 5:
                    message.info = Info.internalBinaryRead(reader, reader.uint32(), options, message.info);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamRecordsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string record_id = 1; */
        if (message.recordId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.recordId);
        /* uint32 record_index = 2; */
        if (message.recordIndex !== 0)
            writer.tag(2, WireType.Varint).uint32(message.recordIndex);
        /* indykite.ingest.v1beta3.RecordError record_error = 3; */
        if (message.error.oneofKind === "recordError")
            RecordError.internalBinaryWrite(message.error.recordError, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.rpc.Status status_error = 4; */
        if (message.error.oneofKind === "statusError")
            Status.internalBinaryWrite(message.error.statusError, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* indykite.ingest.v1beta3.Info info = 5; */
        if (message.info)
            Info.internalBinaryWrite(message.info, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.StreamRecordsResponse
 */
export const StreamRecordsResponse = new StreamRecordsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IngestRecordRequest$Type extends MessageType<IngestRecordRequest> {
    constructor() {
        super("indykite.ingest.v1beta3.IngestRecordRequest", [
            { no: 1, name: "record", kind: "message", T: () => Record, options: { "validate.rules": { message: { required: true } } } }
        ]);
    }
    create(value?: PartialMessage<IngestRecordRequest>): IngestRecordRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<IngestRecordRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IngestRecordRequest): IngestRecordRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* indykite.ingest.v1beta3.Record record */ 1:
                    message.record = Record.internalBinaryRead(reader, reader.uint32(), options, message.record);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IngestRecordRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* indykite.ingest.v1beta3.Record record = 1; */
        if (message.record)
            Record.internalBinaryWrite(message.record, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.IngestRecordRequest
 */
export const IngestRecordRequest = new IngestRecordRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IngestRecordResponse$Type extends MessageType<IngestRecordResponse> {
    constructor() {
        super("indykite.ingest.v1beta3.IngestRecordResponse", [
            { no: 1, name: "record_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "info", kind: "message", T: () => Info }
        ]);
    }
    create(value?: PartialMessage<IngestRecordResponse>): IngestRecordResponse {
        const message = { recordId: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<IngestRecordResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IngestRecordResponse): IngestRecordResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string record_id */ 1:
                    message.recordId = reader.string();
                    break;
                case /* indykite.ingest.v1beta3.Info info */ 5:
                    message.info = Info.internalBinaryRead(reader, reader.uint32(), options, message.info);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IngestRecordResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string record_id = 1; */
        if (message.recordId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.recordId);
        /* indykite.ingest.v1beta3.Info info = 5; */
        if (message.info)
            Info.internalBinaryWrite(message.info, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message indykite.ingest.v1beta3.IngestRecordResponse
 */
export const IngestRecordResponse = new IngestRecordResponse$Type();
/**
 * @generated ServiceType for protobuf service indykite.ingest.v1beta3.IngestAPI
 */
export const IngestAPI = new ServiceType("indykite.ingest.v1beta3.IngestAPI", [
    { name: "StreamRecords", serverStreaming: true, clientStreaming: true, options: {}, I: StreamRecordsRequest, O: StreamRecordsResponse },
    { name: "IngestRecord", options: {}, I: IngestRecordRequest, O: IngestRecordResponse },
    { name: "BatchUpsertNodes", options: {}, I: BatchUpsertNodesRequest, O: BatchUpsertNodesResponse },
    { name: "BatchUpsertRelationships", options: {}, I: BatchUpsertRelationshipsRequest, O: BatchUpsertRelationshipsResponse },
    { name: "BatchDeleteNodes", options: {}, I: BatchDeleteNodesRequest, O: BatchDeleteNodesResponse },
    { name: "BatchDeleteRelationships", options: {}, I: BatchDeleteRelationshipsRequest, O: BatchDeleteRelationshipsResponse },
    { name: "BatchDeleteNodeProperties", options: {}, I: BatchDeleteNodePropertiesRequest, O: BatchDeleteNodePropertiesResponse },
    { name: "BatchDeleteRelationshipProperties", options: {}, I: BatchDeleteRelationshipPropertiesRequest, O: BatchDeleteRelationshipPropertiesResponse }
]);
