name: Release notes
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-latest
    steps:
      - id: release-please
        uses: GoogleCloudPlatform/release-please-action@v4
        with:
          token: ${{ secrets.INDYKITEONE_PAT }}
          release-type: node
          path: indykite_sdk_node
          package-name: indykite-sdk-node
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
