name: Release
concurrency: sdk-release
on:
    release:
        types:
            - published

env:
  BIGQUERY_TABLE: jarvis-dev-268314.deployment_analytics.deployment_events

permissions:
    contents: "read"
    id-token: "write"

jobs:
  release:
    name: Release SDK to npmjs repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: "Install"
        run: |
          cd indykite_sdk_node
          npm install
      - name: "Build"
        run: |
          cd indykite_sdk_node
          npm run build
      - name: "Verify es support of dist package"
        run: |
          cd indykite_sdk_node
          npm run-script check-es
      - name: "Copy README for publish"
        run: |
          cp ./README.md indykite_sdk_node/
          cp ./logo.png indykite_sdk_node/
      - name: "Publish the package"
        run: |
          cd indykite_sdk_node
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
