name: Release
concurrency: sdk-release
on:
    release:
        types:
            - published

env:
  BIGQUERY_TABLE: jarvis-dev-268314.deployment_analytics.deployment_events

jobs:
  release:
    name: Release SDK to npmjs repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: "Install"
        run: |
          cd jarvis_sdk_node
          npm install
      - name: "Build"
        run: |
          cd jarvis_sdk_node
          npm run build
      - name: "Verify es support of dist package"
        run: |
          cd jarvis_sdk_node
          npm run-script check-es
      - name: "Copy README for publish"
        run: |
          cp ./README.md jarvis_sdk_node/
          cp ./logo.png jarvis_sdk_node/
      - name: "Publish the package"
        run: |
          cd jarvis_sdk_node
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Get Version
        run: |
          export VERSION=$(cat jarvis_sdk_node/package.json | jq -r '.version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        if: ${{ always() }}
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY_BQ }}
      - name: Publish Deployment Metadata
        if: ${{ always() }}
        uses: indykite/metadata-publisher@v0
        with:
          version: ${{ env.VERSION }}
          status: ${{ job.status }}
          bigquery_table: ${{ env.BIGQUERY_TABLE }}

