name: Release
concurrency: sdk-release
on:
    release:
        types:
            - published
jobs:
  release:
    name: Release SDK to npmjs repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: "Install"
        run: |
          cd jarvis_sdk_node
          npm install
      - name: "Build"
        run: |
          cd jarvis_sdk_node
          npm run build
      - name: "Verify es support of dist package"
        run: |
          cd jarvis_sdk_node
          npm run-script check-es
      - name: "Copy README for publish"
        run: |
          cp ./README.md jarvis_sdk_node/
          cp ./logo.png jarvis_sdk_node/
      - name: "Publish the package"
        run: |
          cd jarvis_sdk_node
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install CU tool
        run: npm install -g clickup-simple-cli
      - name: Get Version
        run: |
          export VERSION=$(cat jarvis_sdk_node/package.json | jq -r '.version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create CU task
        env:
          CU_list: "186335199"
          CU_token: ${{ secrets.CLICKUPPAT }}
          APP_NAME: "Node.js SDK"
          APP_TAG: "jarvis-sdk-node"
        run: |
          CU_tags="$APP_TAG,$VERSION" cu-cli create -d "Release of $APP_NAME available here: https://www.npmjs.com/package/@indykiteone/$APP_TAG/v/$VERSION" "$APP_NAME - release $VERSION"
